### ISSUE TITLE
Pulse Input value when 0

### ISSUE THREAD

**Issue by johnsonjp34** [ytai/ioio#104]
I'm connected to a 14 Hz source and using the getFrequency() method to show the frequency on the screen. Problem is when I unhook my frequency source or shut it off the last freq remains on the screen even if nothing is connected to the pin or the frequency is 0. 

Any suggestions on how to deal with this in code?

Thanks!

**Comment by ytai** [comment]
This issue has been raised and answered several times on the ioio-users forum. Please search there and open a new post there if you cannot find the answer.
