### ISSUE TITLE
IOIO OTG can't connect to phone or table via otg

### ISSUE THREAD

**Issue by rnavarrobol** [ytai/ioio#106]
Recently buy a IOIO OTG, first connect to bluetooth and I can view the device as IOIO0250, later I connect to my tablet galaxy 10" and recognize it. But a next day never more the bluetooth or connect to tablet, smartphone, no view the IOIO.  When I connect to PC, I can execute any jar.  By example HELLOIOIOCONSOLE.JAR or HELLOIOIOSWING.JAR.  I don't understand what happens.

**Comment by ytai** [comment]
Please raise this question on the ioio-users list. This issue tracker is used to track bugs and feature requests.
