### ISSUE TITLE
Incompatible IOIO firmware

### ISSUE THREAD

**Issue by lsitongia** [ytai/ioio#107]
Hi,
I just got the latest SparkFun IOIO-OTG board and I'm trying IOIOLib from a Mac in order to avoid Android.  I've built the libraries using NetBeans 8, using Java 8 (PureJavaComm, IOIOLib, IOIOLibPC).  I'm trying HelloIOIOConsole for a first try.  Is the firmware in this board too new?  Here's the traceback:

run:
[D/IOIOConnectionRegistry] Successfully added bootstrap class: ioio.lib.pc.SerialPortIOIOConnectionBootstrap
[D/SerialPortIOIOConnectionBootstrap] Adding serial port /dev/tty.usbmodem1a1261
[D/IOIOImpl] Waiting for IOIO connection
[V/IOIOImpl] Waiting for underlying connection
[V/IOIOImpl] Waiting for handshake
[I/IncomingState] IOIO Connection established. Hardware ID: SPRK0020 Bootloader ID: IOIO0400 Firmware ID: IOIO0330
[V/IOIOImpl] Querying for required interface ID
[E/IOIOImpl] Required interface ID is not supported
[E/IOIOBaseApplicationHelper] Incompatible IOIO firmware
ioio.lib.api.exception.IncompatibilityException: IOIO firmware does not support required firmware: IOIO0005
	at ioio.lib.impl.IOIOImpl.checkInterfaceVersion(IOIOImpl.java:208)
	at ioio.lib.impl.IOIOImpl.waitForConnect(IOIOImpl.java:135)
	at ioio.lib.util.IOIOBaseApplicationHelper$IOIOThread.run(IOIOBaseApplicationHelper.java:58)

What should I do next?  Thank you for your work and your help.

**Comment by ytai** [comment]
Either upgrade your firmware (recommended) to v5.x or downgrade your software to v4.x.
In the future, such discussion should be made on the ioio-users mailing list. This issue tracker is for bugs and feature requests.
