### ISSUE TITLE
Detect if current is flowing in external electrical circuit

### ISSUE THREAD

**Issue by snazir** [ytai/ioio#108]
Hi, I have an android app requirement. App should connect to electrical wires switch (a simple light switch) and detects if switch is active (current is flowing). I was thinking of using IOIO board to do the task. I have not used it before and have no knowledge of its exact working and features. So my question is, can IOIO board connect to circuit and detect the flow of current?

The voltage of circuit is probably 12V and max of 16 amps.

**Comment by ytai** [comment]
I saw that you have correctly moved this question to the user group. Will respond there.
