### ISSUE TITLE
App-IOIO0505 Missing IOIOLib Directory's

### ISSUE THREAD

**Issue by ThePieMonster** [ytai/ioio#114]
The App-IOIO0505 download is missing the required files to properly install and use IOIO-OTG v5.06.

https://github.com/ytai/ioio/wiki/Downloads

Compare the contents of App-IOIO0504.zip with App-IOIO0505.zip and you will easily see the missing information.

**Comment by ytai** [comment]
The new version is not a drop in replacement. Specifically, it features a new build system and distribution system and a new directory structure. The new bundle still includes the same functionality as far as I know. Let me know if it's not the case.
I recommend you to read the wiki page about using Gradle with IOIO: https://github.com/ytai/ioio/wiki/Building-IOIO-Applications-With-Gradle

**Comment by ThePieMonster** [comment]
Ah alright thanks for the reply. Just started with this so was a little confused. Do you have a email address where I can contact you at all by any chance?

**Comment by ytai** [comment]
You can post to the ioio-users group.

**Comment by ThePieMonster** [comment]
I posted in the Google group but it hasn't shown up yet. Do you have to approve the post first?
