### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by robinpaulson** [ytai/ioio#231]
Hi, apologies if I've missed this, but I can't see licence info anywhere, other than for the board firmware. Could you point it out to me? Thanks

**Comment by hannesa2** [comment]
Hmm, if nothing is specified, I guess your are free to interpret this. But I'm not sure.
I would vote for Apache

**Comment by robinpaulson** [comment]
Nothing specified almost always means copyright, all rights reserved, same as for any intellectual work.

I'm not a fan of so-called "permissive" licences, but am unwilling to get into an argument of x vs. y.

**Comment by hannesa2** [comment]
Here is a suggestion https://github.com/ytai/ioio/pull/232
