### ISSUE TITLE
Looking for the ioio led matrix apk

### ISSUE THREAD

**Issue by alucardxs** [ytai/ioio#235]
Hi everyone,

I'm looking for the application that manages to send images to the ioio (v1) board in order to be displayed on a 64x64 led matrix.
I wire ma ioio with the led matrix but missing tha pak application now ...
Can't find anywhere ...
Any idea ?

Thanks !

**Comment by hannesa2** [comment]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/3314607/106855050-9aaf5a00-66bc-11eb-86d5-3fe7e1224e1b.png">


Second link has an important sentence

<img width="493" alt="image" src="https://user-images.githubusercontent.com/3314607/106855107-b31f7480-66bc-11eb-9e79-abecd218df2a.png">

which points you to right branch. https://github.com/ytai/ioio/tree/rgb-led Ok, it's 7 years old.....
