### ISSUE TITLE
Waiting for handshake

### ISSUE THREAD

**Issue by chrisws** [ytai/ioio#356]
Hi,

I just bought an ioio-otg board for a project.

I tried the HelloWorldConsole program on various Ubuntu 22.04.3 machines. It never gets past the "Waiting for handshake" step. It works fine on Windows 10. 

I have installed the udev file. There seems to be some associated errors in the syslog. 

Are there any tricks for getting this to work in any recent linux version?

**Comment by chrisws** [comment]
Never mind...

I have a solution in case anyone is interested. I switched over from using purejavacomm to fazecast.
Here's my project: https://github.com/smallbasic/smallbasic.plugins/tree/master/ioio

**Comment by hannesa2** [comment]
Thank you for the solution
