### ISSUE TITLE
RFE: Merge the pwm-improvements branch into the master branch

### ISSUE THREAD

**Issue by ghost** [ytai/ioio#65]
This is a request for enhancement to merge the code from the pwm-improvements branch into the master so it is part the next IOIO Bootloader and Firmware release.

The code in the pwm-improvements branch can be very helpful for UAV projects. 

https://groups.google.com/forum/#!searchin/ioio-users/UAV/ioio-users/8gN0fkkwmnc/FVHphQw1tVsJ

https://groups.google.com/forum/#!searchin/ioio-users/UAV/ioio-users/p68b9kf04oM/28FLxq2tUtAJ

**Comment by ytai** [comment]
The Sequencer API is a strict subset. Will not fix.
