### ISSUE TITLE
IOIO not  recognized  by android 4.4 phones.

### ISSUE THREAD

**Issue by cedeleducatronica** [ytai/ioio#98]
hi,   i  have  two  ioios  ( v 1,   with  311 bootloader and ioio400 firmware)  and  a  IOIO OTG,  the IOIO V1   works  fine (downloading  the  helloIOIO example, led on board  responding)  with   several  phones:
Motorola  razr D1, Android  4.1.2
Huawei ascend P6, android  4.2.2
Samsung  galaxy ace android 2.3.6
also   using  the  ioio hardware tester app,   the  three phones  work  well ( led  responding, show  info)
i  have  another  two phones  in wich  the ioio hardware  test app  does not  work.
Moto x xt1053   android  4.4.4
ZTE II MAX v815w  android 4.4.2

the  ZTE  recognizes   the  ioio v1  i  know  because   i  was  able  to  use  the  ioio camera robot (conected to the  IOIO v1)app,  working  well.

the  moto X  does´nt  recognize  any   of  the  IOIOS   and  I have  not  been  able  to  use  the   IOIO OTG  on  any  phone,   i  have  checked  the  potentiometer,  with   and  without   usb
debugging mode , the  switch  in  both  positions .  i  don´t   know  what   to  do.

i  have  seen   several  answers  on  Google  groups,   talking  about nexus 7, or  5  and  another  phones  but  i  don´t  know  if  i   should  update   the  OTG  firmware. im  really  interested  on  making  any  of  the  ioios  work   with  the  MOTO X  or  android  4.4 because  the phones  are  mine, others not .

**Comment by rodmast** [comment]
I upgrade the ioio-otg but the android 4.4 not recognize the ioio.

**Comment by vivekaris** [comment]
but working fine in android 5.0

On Thu, Aug 6, 2015 at 11:19 AM, rodmast <notifications@github.com> wrote:

> I upgrade the ioio-otg but the android 4.4 not recognize the ioio.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ytai/ioio/issues/98#issuecomment-128252062>.
>



-- 

-----------------------------------------------------------
with regards
------------------------------------------------------------
Vivek Kumar Kanaujia
Technology Evanglist
Kanpur

**Comment by rodmast** [comment]
mm.. I try in android 5.x and not work

**Comment by mohsenpashna** [comment]
Maybe you got another problem, it was working for me since 4.x and now is
working by 5.x. Check the other issues

On Thu, Aug 6, 2015 at 2:56 PM, rodmast <notifications@github.com> wrote:

> mm.. I try in android 5.x and not work
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ytai/ioio/issues/98#issuecomment-128270991>.
>



-- 
Regards.

Mohsen Pashna
PhD candidate,
Centre for Artificial Intelligence and Robotics (CAIRO),
Malaysia-Japan International Institute of Technology (MJIIT), UTM KL Campus.
www.pashna.weebly.com

Telephone:
Malaysia: +60-3-2209 1491
Iran: +98-912 323 9607

**Comment by ytai** [comment]
The IOIO hardware test app is broken (apparantely not built with OpenAccessory support) and is not part of the official IOIO codebase. Specifically, it cannot work with Android >= 4.2 without OpenAccessory support.
Try with the precompiled HelloIOIO.apk provided in the official software bundle.

This discussion belongs on ioio-users if you need to continue.
